.cfignore
circle.yml
manifest.yml
package.json
scripts/render.babel.js

- only use morgan in dev
- don't pass hopst as parameter
- added cloud foundry manifest (tested)
- added circle config (will test when merged)

Initial deployment scripts

---

config/paths.js
src/bundles/CaseStudy/components/CaseStudyForm/CaseStudyForm.js
src/bundles/CaseStudy/components/CaseStudyForm/CaseStudyForm.json
src/bundles/CaseStudy/components/CaseStudyForm/CaseStudyForm.snaps.test.js
src/bundles/CaseStudy/components/CaseStudyForm/CaseStudyForm.test.js
src/bundles/CaseStudy/components/CaseStudyForm/__snapshots__/CaseStudyForm.snaps.test.js.snap
src/bundles/CaseStudy/redux/modules/reducer.js
src/shared/MultiInput/MultiInput.js
src/shared/MultiInput/__snapshots__/MultiInput.snaps.test.js.snap

The state/props object to be passed to this component is the same as `CaseStudyForm.json`

CaseStudy form population

---

config/paths.js
src/bundles/SellerRegistration/StartWidget.js
src/bundles/SellerRegistration/StartWidget.test.js
src/bundles/SellerRegistration/__snapshots__/StartWidget.test.js.snap

Simple start page copied from the prototype
Deed + start url passed as props

Seller registration - start page

---

src/bundles/SellerRegistration/components/YourInfoForm/YourInfoForm.js
src/bundles/SellerRegistration/components/YourInfoForm/YourInfoForm.snaps.test.js
src/bundles/SellerRegistration/components/YourInfoForm/__snapshots__/YourInfoForm.snaps.test.js.snap

For now to change title/button text

Add a mode to the info form

---

src/bundles/CaseStudy/components/CaseStudyForm/StepTwo.js

This will make the optional require work out of the box with server side validation.

Change to required validator

---

config/paths.js
src/__tests__/validators.test.js
src/bundles/ApplicantSignup/components/Signup/Signup.js
src/bundles/ApplicantSignup/redux/modules/signup.js
src/bundles/SellerRegistration/EnterPasswordWidget.js
src/bundles/SellerRegistration/EnterPasswordWidget.test.js
src/bundles/SellerRegistration/__snapshots__/EnterPasswordWidget.test.js.snap
src/bundles/SellerRegistration/components/EnterPasswordForm/EnterPasswordForm.js
src/bundles/SellerRegistration/components/EnterPasswordForm/EnterPasswordForm.json
src/bundles/SellerRegistration/components/EnterPasswordForm/EnterPasswordForm.snaps.test.js
src/bundles/SellerRegistration/components/EnterPasswordForm/EnterPasswordForm.test.js
src/bundles/SellerRegistration/components/EnterPasswordForm/__snapshots__/EnterPasswordForm.snaps.test.js.snap
src/bundles/SellerRegistration/components/EnterPasswordForm/index.js
src/bundles/SellerRegistration/redux/modules/enterpassword.js
src/bundles/SellerRegistration/redux/modules/reducer.js
src/shared/form/Textfield.js
src/validators.js

- Modified TextField to support password
- new min validator

Enter password

---

src/bundles/ApplicantSignup/components/Signup/Signup.js
src/bundles/ApplicantSignup/components/Signup/Signup.test.js
src/bundles/ApplicantSignup/components/Signup/__snapshots__/Signup.snaps.test.js.snap
src/bundles/SellerRegistration/components/Review.js
src/bundles/SellerRegistration/components/Submit.js

@nathf how do I make it redirect to a different page at the end?

Add application review and submit screens

---

config/paths.js
src/bundles/ApplicantSignup/components/Signup/__snapshots__/Signup.snaps.test.js.snap
src/bundles/SellerRegistration/SignupWidget.js
src/bundles/SellerRegistration/SignupWidget.test.js
src/bundles/SellerRegistration/__snapshots__/EnterPasswordWidget.test.js.snap
src/bundles/SellerRegistration/components/EnterPasswordForm/EnterPasswordForm.js
src/bundles/SellerRegistration/components/EnterPasswordForm/EnterPasswordForm.test.js
src/bundles/SellerRegistration/components/EnterPasswordForm/__snapshots__/EnterPasswordForm.snaps.test.js.snap
src/bundles/SellerRegistration/components/SignupForm/SignupForm.js
src/bundles/SellerRegistration/components/SignupForm/SignupForm.snaps.test.js
src/bundles/SellerRegistration/components/SignupForm/SignupForm.test.js
src/bundles/SellerRegistration/components/SignupForm/__snapshots__/SignupForm.snaps.test.js.snap
src/bundles/SellerRegistration/components/SignupForm/index.js
src/bundles/SellerRegistration/components/YourInfoForm/YourInfoForm.js
src/bundles/SellerRegistration/components/YourInfoForm/__snapshots__/YourInfoForm.snaps.test.js.snap
src/bundles/SellerRegistration/redux/modules/reducer.js
src/bundles/SellerRegistration/redux/modules/signup.js

Rather than reusing the your info form...
EDIT: still waiting for StatefulError to be committed to shared for Checkbox error handling, but could be added later

Add a separate seller signup widget

---

package.json
src/bundles/ApplicantSignup/components/Signup/Signup.js
src/bundles/ApplicantSignup/components/Signup/Signup.test.js
src/bundles/ApplicantSignup/components/Signup/__snapshots__/Signup.snaps.test.js.snap
src/bundles/CaseStudy/components/CaseStudyForm/__snapshots__/CaseStudyForm.snaps.test.js.snap
src/bundles/SellerRegistration/__snapshots__/BusinessDetailsWidget.test.js.snap
src/bundles/SellerRegistration/__snapshots__/StartWidget.test.js.snap
src/bundles/SellerRegistration/components/BusinessDetailsForm/BusinessDetailsForm.js
src/bundles/SellerRegistration/components/BusinessDetailsForm/__snapshots__/BusinessDetailsForm.snaps.test.js.snap
src/bundles/SellerRegistration/components/DomainSelector/DomainSelector.js
src/bundles/SellerRegistration/components/DomainSelector/DomainSelector.test.js
src/bundles/SellerRegistration/components/DomainSelector/__snapshots__/DomainSelector.test.js.snap
src/bundles/SellerRegistration/components/DomainSelector/domains.js
src/bundles/SellerRegistration/components/PricingForm/PricingForm.js
src/bundles/SellerRegistration/components/PricingForm/__snapshots__/PricingForm.test.js.snap
src/bundles/SellerRegistration/components/Review.js
src/bundles/SellerRegistration/components/Start.js
src/bundles/SellerRegistration/components/Submit.js
src/bundles/SellerRegistration/components/YourInfoForm/YourInfoForm.js
src/bundles/SellerRegistration/components/YourInfoForm/__snapshots__/YourInfoForm.snaps.test.js.snap
src/shared/Textarea/Textarea.js
src/shared/Textarea/__snapshots__/Textarea.snaps.test.js.snap
yarn.lock

* Disabled submit if all forms arent valid
* Copy updates
* re-arranged some form fields
* Expanded props passed to components

Layout tweak updates

---

src/bundles/SellerRegistration/components/DocumentsForm/DocumentsForm.js
src/bundles/SellerRegistration/redux/modules/application.js
src/shared/reduxModules/__tests__/api.test.js
src/shared/reduxModules/api.js

- removed content-type from api

Refactor DocumentsForm to use redux for api call

---

src/bundles/SellerRegistration/components/DocumentsForm/DocumentsForm.js
src/bundles/SellerRegistration/components/DocumentsForm/DocumentsForm.test.js

- also, display original doc name as link txt

Add some tests for documents

---

config/paths.js
src/bundles/SellerRegistration/components/ApplicationPreview/ApplicationPreview.js
src/bundles/SellerRegistration/components/ApplicationPreview/ApplicationPreview.json

@nathf Is there an easier way to do these templating loops?

Add more fields to application preview

---

src/bundles/SellerRegistration/components/DomainSelector/DomainSelector.js
src/bundles/SellerRegistration/components/DomainSelector/__snapshots__/DomainSelector.test.js.snap

- still saving in .services in model

Save domains not services

---

src/bundles/SellerRegistration/components/Signup/Signup.js
src/bundles/SellerRegistration/components/Signup/Signup.test.js
src/bundles/SellerRegistration/components/Signup/__snapshots__/Signup.snaps.test.js.snap
src/bundles/SellerRegistration/components/YourInfoForm/YourInfoForm.js
src/bundles/SellerRegistration/components/YourInfoForm/__snapshots__/YourInfoForm.snaps.test.js.snap
src/bundles/SellerRegistration/redux/modules/reducer-signup.js

Various changes to business details

---

src/bundles/SellerRegistration/components/DocumentsForm/DocumentsForm.js
src/bundles/SellerRegistration/components/DocumentsForm/DocumentsForm.test.js

- remove the deed from doc list

Update documents copy

---

src/bundles/CaseStudy/components/CaseStudyForm/CaseStudyForm.js
src/bundles/CaseStudy/components/CaseStudyForm/__snapshots__/CaseStudyForm.snaps.test.js.snap
src/bundles/CaseStudy/components/DomainList/DomainList.js
src/bundles/SellerRegistration/__snapshots__/StartWidget.test.js.snap
src/bundles/SellerRegistration/components/BusinessInfoForm/BusinessInfoForm.js
src/bundles/SellerRegistration/components/BusinessInfoForm/BusinessInfoForm.test.js
src/bundles/SellerRegistration/components/DomainSelector/DomainSelector.js
src/bundles/SellerRegistration/components/DomainSelector/__snapshots__/DomainSelector.test.js.snap
src/bundles/SellerRegistration/components/Signup/__snapshots__/Signup.snaps.test.js.snap
src/bundles/SellerRegistration/components/Start.js

Also added a test for the BusinessInfoForm

Minor copy tweaks

---

src/bundles/SellerRegistration/components/DocumentsForm/DocumentsForm.js
src/bundles/SellerRegistration/components/DocumentsForm/DocumentsForm.test.js
src/bundles/SellerRegistration/redux/modules/reducer-signup.js
src/shared/form/Datefield.js

Triple-text-box date component added.
Needs better testing but works for now.

expiry dates on document page using new datefield component

---

src/bundles/CaseStudy/__snapshots__/CaseStudyViewWidget.test.js.snap
src/bundles/CaseStudy/components/DomainList/DomainList.js
src/bundles/CaseStudy/components/View/View.js
src/bundles/CaseStudy/components/View/__snapshots__/View.test.js.snap
src/bundles/SellerRegistration/components/ApplicationPreview/ApplicationPreview.js
src/bundles/SellerRegistration/components/ConnectedLink.js
src/bundles/SellerRegistration/components/Finish.js
src/bundles/SellerRegistration/components/Review.js
src/bundles/SellerRegistration/redux/helpers.js
src/bundles/SellerRegistration/redux/modules/application.js
src/shared/SellerProfile/ReviewHeader.js

Dispatch event on specific link clicks to focus heading on next screen, doesnt feel good.

Connected link

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
scripts/test.js
server/routes/render.js
server/routes/render.test.js
src/shared/SellerProfile/ReviewHeader.js
src/shared/SellerProfile/ReviewHeader.test.js
src/shared/SellerProfile/Row.js
src/shared/SellerProfile/profile.css
yarn.lock

First pass at using CSS modules in DMP.

CSS modules

---

src/bundles/Search/components/Catalogue/Catalogue.css
src/bundles/Search/components/Catalogue/Catalogue.js
src/shared/Card/Card.css
src/shared/Card/Card.js
src/shared/LocalNav/LocalNav.js

Put the mobile search filter in an accordion

Mobile search accordian

---

src/bundles/CaseStudy/components/DomainList/DomainList.js
src/bundles/CaseStudy/components/StepLink.js
src/bundles/SellerRegistration/components/ApplicationPreview/ApplicationPreview.js
src/bundles/SellerRegistration/components/ConnectedLink.js
src/bundles/SellerRegistration/components/Signup/Signup.js
src/bundles/SellerRegistration/redux/modules/application.js

Refactor anchors to Links

---

src/bundles/SellerRegistration/components/RecruiterForm/RecruiterForm.js
src/bundles/SellerRegistration/components/Submit.js

Fix for not recruiter

---

src/bundles/Search/components/Catalogue/Catalogue.css
src/bundles/Search/components/Catalogue/Catalogue.js

superficial interface changes as requested by N

remove found on result count, hide sort by, add casestudies tab

---

src/bundles/SellerRegistration/ApplicantSignup.json
src/shared/SellerProfile/Body.js
yarn.lock

adding address to review page (array with keys)

Address Review Add

---

src/shared/form/Datefield.js

This was picked up by the console dev tools

Should not set state in constructor

---

src/RegisterComponent.js
src/bundles/SellerRegistration/__snapshots__/BusinessDetailsWidget.test.js.snap
src/bundles/SellerRegistration/components/BusinessDetailsForm/__snapshots__/BusinessDetailsForm.snaps.test.js.snap
src/bundles/SellerRegistration/components/DomainSelector/__snapshots__/DomainSelector.test.js.snap
src/bundles/SellerRegistration/components/ProductsForm/ProductsForm.js
src/bundles/SellerRegistration/components/Signup/__snapshots__/Signup.snaps.test.js.snap
src/bundles/SellerRegistration/components/Start.js
src/bundles/SellerRegistration/components/StepNav/StepNav.js
src/bundles/SellerRegistration/components/YourInfoForm/__snapshots__/YourInfoForm.snaps.test.js.snap
src/bundles/SellerRegistration/redux/helpers.js
src/bundles/SellerRegistration/redux/modules/application.js
src/shared/SaveError.js

- removing react-axe for dev - it causes my local browser to crash
- display error message when api call fails
- trying to prevent null products from being saved

Add an error message when application cannot save

---

src/bundles/CaseStudy/components/DomainList/CaseStudy.js
src/bundles/CaseStudy/components/DomainList/DomainList.js
src/bundles/CaseStudy/components/DomainList/DomainList.test.js
src/bundles/CaseStudy/redux/modules/reducer.js
src/bundles/SellerRegistration/components/BusinessDetailsForm/BusinessDetailsForm.js
src/bundles/SellerRegistration/components/BusinessDetailsForm/BusinessDetailsForm.test.js
src/bundles/SellerRegistration/components/DocumentsForm/DocumentsForm.js
src/bundles/SellerRegistration/components/DomainSelector/DomainSelector.js
src/bundles/SellerRegistration/components/Review.js
src/bundles/SellerRegistration/components/Review.test.js
src/bundles/SellerRegistration/components/Start.js
src/bundles/SellerRegistration/components/Start.test.js
src/bundles/SellerRegistration/components/StepNav/StepNav.js
src/bundles/SellerRegistration/components/YourInfoForm/YourInfoForm.js
src/bundles/SellerRegistration/components/YourInfoForm/YourInfoForm.test.js

- Had to use isNumber() to cater for supplierCode 0
- Minor tweaks to some components that didn't previously have unit tests

Fix supplier code and add some tests

---

config/paths.js
src/bundles/ApplicationsAdmin/AssessmentsAdmin.json
src/bundles/ApplicationsAdmin/AssessmentsAdminWidget.js
src/bundles/ApplicationsAdmin/components/AssessmentList/AssessmentList.css
src/bundles/ApplicationsAdmin/components/AssessmentList/AssessmentList.js
src/bundles/ApplicationsAdmin/components/AssessmentList/AssessmentList.test.js
src/bundles/ApplicationsAdmin/components/AssessmentList/index.js
src/bundles/ApplicationsAdmin/redux/modules/reducer.js

Buttons, etc to be wired up later

Assessment list

---

.gitignore
docs/testing.md
src/bundles/SellerRegistration/ApplicantSignup.json
src/bundles/SellerRegistration/components/ProductsForm/ProductsForm.js
src/bundles/SellerRegistration/redux/modules/__tests__/steps.test.js
src/bundles/SellerRegistration/redux/modules/steps.js

Navigation changes depending on products/services selected. Tests

Seller rego noproducts nav

---

src/bundles/SellerRegistration/components/ApplicationPreview/ApplicationPreview.json
src/shared/SellerProfile/Body.js
src/shared/SellerProfile/SellerProfile.css

Fix documents section seller profile

---

src/shared/SellerProfile/Body.js

Made this link optional based on state of assessed/unassessed

Hide learn about assessments ink

---

src/bundles/SellerRegistration/components/ApplicationPreview/ApplicationPreview.json
src/shared/SellerProfile/Body.js
src/shared/SellerProfile/SellerProfile.css

add financial statement to documents list
add mailto for email in callout

Add financial statements to documents

---

src/shared/SellerProfile/Body.js

fix logic that conditionally shows link

fix logic that conditionally shows link

---

src/bundles/Search/components/Catalogue/Catalogue.json
src/bundles/SellerRegistration/ApplicantSignup.json
src/bundles/SellerRegistration/components/ProductsForm/ProductsForm.js
src/bundles/SellerRegistration/components/Signup/Signup.js
src/bundles/SellerRegistration/components/Submit.js
src/bundles/SellerRegistration/redux/modules/application.js
src/shared/SellerProfile/Body.js
src/shared/SellerProfile/PrivateInfo.js

Added logic to application.js reducer that evaluates some forms for
empty data and resets their completion status if empty. Gets called in
NavigateToStep action creator.

Casestudies step completion validation

---

package.json
src/bundles/SellerRegistration/components/Signup/Signup.js
yarn.lock

only change was the withRouter() function:
https://github.com/ReactTraining/react-router/pull/4684

upgrade to react router 4.1.1

---

src/bundles/ApplicationsAdmin/components/AppList/AppList.js
src/bundles/SellerRegistration/components/ApplicationPreview/ApplicationPreview.js
src/bundles/SellerRegistration/components/DomainSelector/DomainSelector.js
src/bundles/SellerRegistration/components/RecruiterForm/RecruiterForm.js
src/bundles/SellerRegistration/components/Signup/Signup.js
src/bundles/SellerRegistration/components/Signup/__snapshots__/Signup.snaps.test.js.snap

Change seller rego steps if seller is recruiter and provides services

Allow sellers to be both recruiter and provide services

---

src/bundles/BuyerDashboard/BuyerDashboardWidget.js
src/bundles/BuyerDashboard/components/Dashboard/BuyerDashboard.css
src/bundles/BuyerDashboard/components/Dashboard/__snapshots__/BuyerDashboard.test.js.snap
src/bundles/BuyerDashboard/components/DashboardBriefs/DashboardBriefs.css
src/bundles/BuyerDashboard/components/DashboardBriefs/DashboardBriefs.js
src/bundles/BuyerDashboard/components/DashboardBriefs/__snapshots__/DashboardBriefs.test.js.snap
src/bundles/BuyerDashboard/components/TeamOverview/TeamOverview.css
src/bundles/BuyerDashboard/components/TeamOverview/TeamOverview.js
src/bundles/BuyerDashboard/components/TeamOverview/__snapshots__/TeamOverview.test.js.snap
src/bundles/BuyerDashboard/components/TeamView/TeamView.js
src/bundles/BuyerDashboard/components/TeamView/index.js
src/bundles/BuyerDashboard/redux/modules/reducer.js

component so allow switching between that and new one.
Change team briefs links to view only not edit etc

Allow for feature flag: old jinja template linked to team view

---

src/bundles/ApplicationsAdmin/components/AppChanges/AppChanges.test.js
src/bundles/ApplicationsAdmin/components/AppChanges/helper.js

Doubles the number of ignored fields re application changes list

App changes field validation

---

src/bundles/ApplicationsAdmin/components/AppList/AppList.js
src/bundles/ApplicationsAdmin/components/RevertNotification/RevertNotification.js
src/bundles/ApplicationsAdmin/redux/modules/applications.js

maintain email message if api call fails
better display of revert response

revert email mvp2

---

app/actions/index.js
app/components/Header/Header.js
server/routes/render.js

if client:
- we don't need to set host
- browser will take care of sending cookie

remove host + cookie

---

app/components/SignupForm/SignupForm.js
app/components/shared/form/ErrorBox.js
app/components/shared/reduxModules/errorMessageSelector.js
app/components/validators.js
app/reducers/errorMessage.js
app/reducers/index.js
config/webpack.config.dev.js
package.json

Fixed styling
Manager details requested for contractor not employee

Fresh branch with signup form

---

src/bundles/SellerRegistration/components/Signup/Signup.js

Looks like this was introduced when we added "Allow sellers to be both recruiter and provide services"
Seems some vars were being used before being set

allow recruiters to be submitted

---

circle.yml
package.json

Reverts AusDTO/dto-digitalmarketplace-frontend#477

Revert "upgrade to new node"

---

app/App.js
app/actions/memberActions.js
app/components/CreateUser/CreateUserForm.js
app/components/SignupForm/SignupContainer.js
app/routes.js

move createUser out of /signup

use /2 as new react root path

---

config/webpack.config.dev.js
config/webpack.config.prod.js

fix polyfills

---

src/bundles/CaseStudy/components/DomainList/DomainList.js

I'm not sure how this previously worked

case study form had no csrf token

---

apps/marketplace/pages/ResetPasswordPage.js
apps/orams/pages/LoginPage.js
apps/orams/pages/ResetPasswordPage.js

orams framework slug should be lowercase

ensure users are logged out when resetting password

---

apps/marketplace/components/Reports/ReportView.js
apps/marketplace/components/Reports/ReportView.scss
apps/marketplace/pages/ReportPage.js

update insight report

---

circle.yml
manifest.yml
scripts/cf_run_app.sh
scripts/ups_as_envs.py

Not sure whether this will work, given that it's invoking Python in a nodejs buildpack, but figured trying it would be a fine way to test. :)

Switch to autopilot, use user-provided-services

---

apps/marketplace/components/Reports/ReportView.js
apps/marketplace/pages/ReportPage.js

This reverts commit 3f332d38236830879fee1a6a5467b3c7ec98f733.

Revert "revert dec insights (#604)"

---

apps/marketplace/components/SellerDashboard/SellerDashboard.js
apps/marketplace/components/SellerDashboard/SellerDashboard.scss
apps/marketplace/components/SellerDashboard/SellerDashboard.test.js
apps/marketplace/components/SellerDashboard/__snapshots__/SellerDashboard.test.js.snap
apps/marketplace/pages/SellerDashboardPage.js
package-lock.json
package.json

- dashboard still not hooked up to nav

final changes for seller dashboard

---

apps/marketplace/reducers/index.js

api (https://github.com/AusDTO/dto-digitalmarketplace-api/pull/415/commits/3b75b05188de4a0e92279cc9d0472244701241ad) needs to be released first before this one

add dayRate back to init

---

apps/marketplace/components/Reports/ReportView.js
apps/marketplace/pages/ReportPage.js

Update insights page for February

---

apps/marketplace/components/Collaborate/funded.json
package.json
scripts/smart_city_scraper.js

Use google chrome project for scraping https://github.com/GoogleChrome/puppeteer

Convert to puppeteer from phantomjs

---

apps/marketplace/actions/memberActions.js
apps/marketplace/components/SignupForm/SignupForm.js
apps/marketplace/components/validators.js
apps/marketplace/constants/messageConstants.js
apps/marketplace/pages/SignupPage.js

[Signup] Allow whitelisted buyers without *.gov.au addresses to sign up

---

src/bundles/SellerRegistration/components/PricingForm/PricingForm.js
src/bundles/SellerRegistration/components/PricingForm/PricingForm.test.js
src/bundles/SellerRegistration/components/PricingForm/__snapshots__/PricingForm.test.js.snap
src/bundles/SellerRegistration/components/Signup/Signup.js
src/bundles/SellerRegistration/redux/modules/reducer-signup.js

[Domain pricing] Display maximum price on Pricing page

---

src/bundles/SellerRegistration/components/PricingForm/PricingForm.js
src/bundles/SellerRegistration/components/PricingForm/__snapshots__/PricingForm.test.js.snap

[Domain pricing] Remove VFM message on Pricing page

---

.eslintrc
apps/marketplace/components/Brief/Assessors/BriefInviteAssessorsForm.js
apps/marketplace/components/Brief/Assessors/BriefInviteAssessorsForm.scss
apps/marketplace/components/Brief/Assessors/BriefInviteAssessorsForm.test.js
apps/marketplace/pages/BriefAssessorsPage.js
apps/marketplace/reducers/index.js
apps/marketplace/routes.js
public/custom.css

This is styling for the invite assessors page - there is no redux/integration as of yet.
Used this to clarify requirements for this component.  I plan to merge this as it is not currently linked from anywhere.

Mar 1924 - Invite assessors

---

src/bundles/SellerRegistration/components/PricingForm/PricingForm.js
src/bundles/SellerRegistration/components/PricingForm/__snapshots__/PricingForm.test.js.snap

This pull request updates content on the pricing form.
**Current text**
**Updated text**
Addresses MAR-2252

[Application] Update content for the pricing form

---

src/bundles/SellerRegistration/components/PricingForm/PricingForm.js
src/bundles/SellerRegistration/components/PricingForm/__snapshots__/PricingForm.test.js.snap

[Application] Break up pricing form paragraph

---

apps/marketplace/actions/supplierActions.js
apps/marketplace/components/SellerSelect/SellerSelect.js
apps/marketplace/components/SellerSelect/SellerSelect.scss
apps/marketplace/components/SellerSelect/SellerSelect.test.js

This is an initial stab at a standalone React component for a supplier search input, with auto complete suggestions for results that match the current query.
This has not yet been tested for a11y.

Mar 2376 seller search component

---

public/custom.css

Increase header text size.

---

src/bundles/SellerRegistration/components/PricingForm/PricingForm.js
src/bundles/SellerRegistration/components/PricingForm/__snapshots__/PricingForm.test.js.snap

This pull request updates the SFIA link on the pricing form (Zendesk links need to be updated too).
Addresses #MAR-2653

[Application] Update link to SFIA version 7

---

apps/marketplace/components/Footer/AUFooter.js

[Footer] Update about us link

---

apps/marketplace/components/Brief/BriefATMResponseForm.js
apps/marketplace/components/Brief/BriefATMResponseSubmitted.js
apps/marketplace/components/Brief/BriefRFXResponseForm.js
apps/marketplace/components/Brief/BriefRFXResponseSubmitted.js
apps/marketplace/components/Brief/BriefTrainingResponseForm.js
apps/marketplace/components/Brief/BriefTrainingResponseSubmitted.js
apps/marketplace/components/BuyerATM/BuyerATMCompleted.js
apps/marketplace/components/BuyerATM/BuyerATMReviewStage.js
apps/marketplace/components/BuyerRFX/BuyerRFXCompleted.js
apps/marketplace/components/BuyerRFX/BuyerRFXReviewStage.js
apps/marketplace/components/Opportunity/Opportunity.js
apps/shared/ClosedDate.js

Updating the date formats to conform with the DSS/add the year in certain places.
Updated format example:
From:
2 April
To:
Tuesday 2 April 2019

Mar 2793 Updating date formats to DSS

---

apps/marketplace/components/SkipToLinks/SkipToLinks.js
apps/marketplace/components/SkipToLinks/SkipToLinks.scss
apps/marketplace/index.js
package-lock.json
package.json

This pull request adds skip to content and navigation links.
Addresses MAR-3387

[a11y] Add skip to links

---

apps/marketplace/components/BuyerDashboard/BuyerDashboardBriefTable.js

[Dashboard] Set default name for all draft opportunity types

---

apps/marketplace/components/BuyerSpecialist/BuyerSpecialistAdditionalInformationStage.js

[Specialist] Remove top margin from document paragraph on additional information stage

---

apps/marketplace/components/BuyerDashboard/BuyerDashboard.scss
apps/marketplace/components/BuyerDashboard/BuyerDashboardHeader.js
public/custom.css

This pull request adjusts the styles on the accordion buyers use to create new opportunities.
Addresses MAR-3450

[Dashboard] Fix placement of the buyer new request accordion

---

src/shared/SellerProfile/Body.js
src/shared/SellerProfile/PrivateInfo.js

This pull request fixes up incorrect references to properties which was preventing seller profiles from loading.
Addresses MAR-3423

[Signed agreement] Fix reference to undefined properties

---

apps/marketplace/components/Brief/BriefSubmitted.js
apps/marketplace/components/Opportunity/Opportunity.js
apps/marketplace/components/SellerDashboard/Opportunities.js

This effectively reverts https://github.com/AusDTO/dto-digitalmarketplace-frontend/pull/878 but does so while also fixing the issue where the time on the seller dashboard was localised.

Revert back to Canberra closing time language

---

src/bundles/SellerRegistration/components/BusinessInfoForm/BusinessInfoForm.js

This prevents the user from choosing "More than 200" employees and the SME flag.

Add validation for the SME flag based on employee number

---

apps/marketplace/components/BuyerRFX/BuyerRFXResponseFormatsStage.js
apps/marketplace/components/BuyerTraining/BuyerTrainingResponseFormatsStage.js
package.json

Reverts AusDTO/dto-digitalmarketplace-frontend#893

Revert "Mar 3500"

---

apps/marketplace/components/SellerAssessment/SellerAssessmentCompleted.js
apps/marketplace/components/SellerAssessment/SellerAssessmentIntroductionStage.js

https://govausites.atlassian.net/browse/MAR-3964

mar-3964-Warning content for assessments submitted less than 2 days before an opportunity closing date

---

src/bundles/SellerRegistration/components/DocumentsForm/DocumentsForm.js

merged into RC - so feel free to test it out =)
https://govausites.atlassian.net/browse/MAR-3985
There are 2 changes:
Changed the text of 'choose file' to 'Change file' when a file has been selected.
Make the 'Change file' button pop up with an option to change the file that has been added. Previously the 'choose file' was static.

Mar-3985.2 - Fixing uploading file bug

---

apps/marketplace/components/Brief/Edit/EditOpportunityDocuments.js
apps/marketplace/components/Brief/Edit/EditOpportunitySellers.js

This pull request extends the conditions that determine when to display the closing soon page alert when editing sellers and documents.
Addresses MAR-4171

Show closing soon page alert after edits have been made

---

apps/marketplace/components/SellerAssessment/SellerAssessmentCriteriaStage.js
apps/marketplace/components/SellerAssessment/SellerAssessmentEvidenceStage.js
apps/marketplace/components/SellerAssessment/SellerAssessmentFeedback.js
apps/marketplace/components/SellerAssessment/SellerAssessmentFeedback.scss
apps/marketplace/components/SellerAssessment/SellerAssessmentReviewStage.js
apps/marketplace/pages/SellerAssessmentFlowPage.js
src/bundles/ApplicationsAdmin/components/EvidenceAssessment/EvidenceAssessment.css
src/bundles/ApplicationsAdmin/components/EvidenceAssessment/EvidenceAssessment.js

This pull request adds support for the new platform integration category.

Add the platforms integration category

---

.circleci/config.yml

This pull request changes the deployment of the production clone environment to match other test environments so that it can be used as an environment where emails are not sent by the system.

Deploy to PC on branch changes

---

apps/marketplace/components/Header/Header.js
public/custom.css
src/bundles/Header/Header.js

This pull requests adds a banner to the header to warn users about upcoming maintenance.

Add maintenance banner

---

apps/marketplace/components/Header/Header.js
public/custom.css
src/bundles/Header/Header.js

This reverts commit 186475668ada6c87af568e1caf03ea6c9b6b564d.

HM-4289: Remove maintenance banner

---

.circleci/config.yml

This pull request replaces a deprecated legacy CircleCI image with a next-generation convenience image.

HM-3978: Update CircleCI images

---

apps/marketplace/components/Opportunity/Opportunity.js
apps/marketplace/components/helpers.js
apps/marketplace/components/helpers.test.js

This pull request adds a helper function to determine opportunity type and adds opportunity type as a displayed field on the opportunity page.

HM-4631: Opportunity type

---

apps/marketplace/components/Header/Header.js
public/custom.css
src/bundles/Header/Header.js

This pull request adds a site-wide announcement banner.

HM-4694: Announcement banner

---

apps/marketplace/components/Header/Header.js
src/bundles/Header/Header.js

This pull request changes the hyperlink in the banner to open in a new window.

HM-4694: Announcement banner (fix)

---

apps/marketplace/components/Opportunity/Opportunity.js

This pull request displays key dates/project milestones (when provided) on the opportunity page for Ask The Market opportunities. The field is only displayed to the buyer and to sellers who can respond to the opportunity.

HM-4588: ATM Timeframe Key Dates/Project Milestones

---

apps/marketplace/components/Header/Header.js
apps/marketplace/pages/BuyICTPage.js
apps/marketplace/pages/LoginPage.js
apps/marketplace/routes.js
src/bundles/Header/Header.js

This pull request redirects a logged-in user to the front page (instead of the opportunities page), when no redirect has been specified.

HM-4871: Front page redirection

---

apps/marketplace/components/SellerAssessment/SellerAssessmentCriteriaStage.js
apps/marketplace/components/SellerAssessment/SellerAssessmentEvidenceStage.js
apps/marketplace/components/SellerAssessment/SellerAssessmentIntroductionStage.js
apps/marketplace/components/SellerAssessment/SellerAssessmentRateStage.js
apps/marketplace/components/SellerAssessment/SellerAssessmentReviewStage.js
apps/marketplace/components/SellerDashboard/Categories.js
apps/marketplace/components/SignupForm/SignupForm.js
src/bundles/SellerRegistration/components/Signup/Signup.js
src/bundles/SellerRegistration/components/Signup/__snapshots__/Signup.snaps.test.js.snap
src/bundles/SellerRegistration/components/Start.js

This pull request adds page alerts to advise of upcoming changes to application, profile edit and category assessment submissions.

HM-5071: Lockout banners

---

apps/marketplace/components/SignupForm/SignupForm.js
src/bundles/SellerRegistration/__snapshots__/BusinessDetailsWidget.test.js.snap
src/bundles/SellerRegistration/components/BusinessDetailsForm/__snapshots__/BusinessDetailsForm.snaps.test.js.snap
src/bundles/SellerRegistration/components/DomainSelector/__snapshots__/DomainSelector.test.js.snap
src/bundles/SellerRegistration/components/PricingForm/__snapshots__/PricingForm.test.js.snap
src/bundles/SellerRegistration/components/Signup/Signup.js
src/bundles/SellerRegistration/components/Signup/__snapshots__/Signup.snaps.test.js.snap
src/bundles/SellerRegistration/components/StepNav/StepNav.js
src/bundles/SellerRegistration/components/Submit.js
src/bundles/SellerRegistration/components/YourInfoForm/YourInfoForm.test.js
src/bundles/SellerRegistration/components/YourInfoForm/__snapshots__/YourInfoForm.snaps.test.js.snap

This pull request prevents sellers from creating an account or submitting a new application. 
Page alerts are shown on the sign up form for sellers and on the _Continue Application_ page.

HM-5077: Prevent new seller sign ups and applications

---

public/custom.css

This pull request updates the styling of global BuyICT announcement banner.

HM-5160: Page banner
