AusDTO/dto-digitalmarketplace-frontend

- src/bundles/Search/components/Catalogue/Catalogue.js
obj has search results number > 0 which broke the messaging
> for logged out case studies, cards obj can be empty while pagination

- manifest.yml
I've uploaded buildpack v1.6.6 to `y-cld` - same as what is currently on `z-cld`.
Let's use that for now so that prod and staging can both use v8.2.1.
Let's update to a newer version once we're off the legacy prod env.
> Use old buildpack for node for compat with prod

- manifest-prod.yml
- manifest.yml
- server/render.js
removing bound route to /orams since standalone ORAMs will use this route.
DO NOT RELEASE until after 14th June 2018.  Stand-alone ORAMs scheduled to go live on 13th June COB.
> Remove /orams route

- src/bundles/SellerRegistration/redux/helpers.js
This PR: fixes an issue where sellers with previously removed domains are seeing the "Missing pricing" error in the seller application.
> Daily rate check fix

- src/bundles/SellerRegistration/components/Signup/__snapshots__/Signup.snaps.test.js.snap
- src/bundles/SellerRegistration/components/YourInfoForm/YourInfoForm.js
- src/bundles/SellerRegistration/components/YourInfoForm/__snapshots__/YourInfoForm.snaps.test.js.snap
This PR affects the seller application contact page by:
* Removing the wording that suggests users need to contact us to change who the auth rep is.
* Add H2 headers to separate the Auth rep and Business contact sections
* Move the auth rep fields above business contact fields
> Auth rep changes in seller application

- src/bundles/CaseStudy/components/CaseStudyForm/CaseStudyForm.js
- src/bundles/CaseStudy/components/CaseStudyForm/__snapshots__/CaseStudyForm.snaps.test.js.snap
- src/bundles/SellerRegistration/components/Signup/__snapshots__/Signup.snaps.test.js.snap
- src/bundles/SellerRegistration/components/YourInfoForm/YourInfoForm.js
- src/bundles/SellerRegistration/components/YourInfoForm/__snapshots__/YourInfoForm.snaps.test.js.snap
This adds the following description to phone number fields in the seller registration / application flow: 
> Please include the area code for landlines
Addresses MAR-1800
> [Seller Registration] Add descriptions to phone fields

- src/bundles/CaseStudy/components/SubmitConfirmation/SubmitConfirmation.js
This adds a link to the training template sellers can download while their assessment is being processed.
Addresses MAR-2140
> [Case Study] Update brief response template links

- views/index.ejs
This pull request prevents the `animate.js` and `accordion.js` scripts from loading on every page.
> [Views] Remove references to accordion and animate scripts

- src/bundles/SellerRegistration/redux/helpers.js
- src/bundles/SellerRegistration/redux/helpers.test.js
This pull request:
* Adds more tests for the `pruneModel` function
* Prunes products if they're empty.  Application edits couldn't be approved when empty products existed (eg. `{'0': {}`). 
* Checks the value of `recruiter` before pruning recruitment information
Addresses MAR-2347
> [Application] Improve how products and recruiter info is pruned

- apps/marketplace/components/Footer/AUFooter.js
The National Innovation and Science Agenda website was archived in July.  This pull request updates the links to its new home.
Addresses MAR-2354
> [Footer] Update NISA link

- src/shared/SellerProfile/PrivateInfo.js
These checks are being added after the following error was captured by Rollbar (seller application that had no documents).
> TypeError: Cannot read property 'noWorkersCompensation' of undefined
Addresses MAR-2353
> [Seller profile] Add checks before displaying workers compensation message

- public/custom.css
Fix the header signup and login button :focus states so they are the same as :hover. Currently, the :focus state produces the following:
> Fix the header signup and login button :focus states

- apps/marketplace/components/Opportunities/Opportunities.test.js
Remove two problematic assertions that will fail when the current date and future dates span two different timezone configs (e.g. day light saving)
> Fix opportunities test

- apps/marketplace/components/Brief/BriefATMResponseForm.js
- apps/marketplace/components/Brief/BriefRFXResponseForm.js
This PR will adjust the ATM and RFX brief response file input elements to accept the same file extensions as the file input elements in the ATM and RFX brief flows, to fix an issue where a buyer can upload a response template in a format a seller can't upload in their response.
> Adjust the accepted file extensions on ATM and RFX brief responses

- apps/marketplace/components/Opportunity/Opportunity.js
A yet unidentified issue results in a file attachment in a RFX (and possibly other flows) brief being stored as "null". This causes an uncaught exception when viewing the brief (which results in a blank white screen). This PR prevents null values from causing an issue.
> Fix issue where null filename causes issues on opportunity pages

- src/bundles/CaseStudy/components/DomainList/DomainList.js
- src/bundles/CaseStudy/components/DomainList/DomainList.test.js
This PR will add a warning message to the seller profile flow on the case study stage, warning them of the incoming changes to the assessment process.
We don't yet have a firm date on the new assessment flow release, but this warning message will be released ~2 weeks before the new flow release.
> Add a warning message to the case study stage in seller profile.

- apps/marketplace/components/Footer/AUFooter.js
This pull request updates footer links so they point to the new Zendesk pages.
Addresses MAR-3320
> [Footer] Update terms of use, privacy, security, disclaimer and copyright links

- src/bundles/SellerRegistration/components/DocumentsForm/DocumentsForm.js
- src/bundles/SellerRegistration/components/ProductsForm/ProductsForm.js
- src/bundles/SellerRegistration/components/Signup/__snapshots__/Signup.snaps.test.js.snap
- src/bundles/SellerRegistration/components/Start.js
- src/bundles/SellerRegistration/components/ToolsForm/ToolsForm.js
This is to be released with the new seller assessment flow - late changes to the seller profile edit flow to remove text references to case studies.
> Remove case study references from seller profile flow

- apps/marketplace/components/SellerSelect/SellerSelect.js
- apps/marketplace/components/SellerSelect/SellerSelect.test.js
- src/bundles/Search/redux/modules/search.js
This PR changes the seller select component (used in RFX flow) and the seller catalogue search to trigger/allow searching when a minimum of 2 characters are provided, rather than 3. This is to address the issue where sellers with only two characters in their name required appending the `%` wildcard to be selectable/searchable.
> Allow searching for sellers with 2 characters

- package-lock.json
- package.json
`npm install` fails due to `'sinon@7.4.0' is not in the npm registry`.  See [https://github.com/sinonjs/sinon/issues/2071](https://github.com/sinonjs/sinon/issues/2071) for more information.
> [Packages] Bump sinon to v7.4.1

- apps/shared/form/CheckboxDetailsField.js
This `onChange()` property on the shared checkbox is not being used anywhere in code, and complicates its API, so this PR is removing it.
> Remove the onChange from the shared Checkbox component

- apps/marketplace/components/Opportunity/OpportunitySpecialistInfoCard.js
When a new draft specialist opportunity is created, the card is missing the number of candidates that can be submitted.  This pull request sets the default prop to 6.
Addresses MAR-3387
> [Opportunity] Set default number of specialist candidates

- apps/marketplace/components/Opportunity/OpportunitySpecialistInfoCard.js
- apps/marketplace/components/Opportunity/OpportunitySpecialistInfoCard.test.js
This pull request adjusts the message that's displayed on the information card when only one candidate can be submitted.
Addresses MAR-3387
> [Specialist] Fix message when one candidate can be submitted

- apps/marketplace/components/Brief/BriefATMResponseForm.js
- apps/marketplace/components/Brief/BriefRFXResponseForm.js
- apps/marketplace/components/Brief/BriefTrainingResponseForm2.js
In MAR-3562, bad data was discovered in a seller's response which may be an indicator that they submitted their response before their file finished uploading.  This pull request addresses this by adding the missing `uploading` prop.
> [Responses] Add missing prop to prevent submission during file upload

- apps/marketplace/components/ProgressFlow/ProgressContent.js
- apps/shared/form/FileInput.js
This reverts https://github.com/AusDTO/dto-digitalmarketplace-frontend/pull/827, as this broke file uploads in Safari due to how Safari prevents JS from executing click events on button elements that were not clicked on by the user.
This is a quick fix to allow Safari file uploading again while a Safari compatible solution is sought for the previous a11y file uploading ticket.
> Revert "[a11y] Make the file upload accessible via keyboard (#827)"

- src/shared/SellerProfile/ReviewHeader.js
On a seller profile, the 'update profile' card's heading says 'Update the services you offer',
it is now changed to 'Update your company details
> mar-3348 - updating content on seller profile

- src/shared/Badges/Badges.js
https://github.com/AusDTO/dto-digitalmarketplace-frontend/pull/808/files changed the way the badges work on the supplier's profile page but seemingly broke the 'Recruiter' badge from showing up in the supplier catalogue search result cards, as the cards are given a true/false `recruiter` property. This PR restores the `recruiter` badge property to accomodate the search result cards but shouldn't affect the full profile page.
> Add recruitment badge for seller catalogue search result cards

- package.json
This PR bumps the node version since Cloud Foundry have dropped support for v8 from their build packs.
> [Packages] Bump node engine

- src/bundles/ApplicationsAdmin/components/Agency/Agency.js
There is currently an issue in the admin portal, where by Edge users can't save agency details, because the form save uses the `Object.fromEntries` API, which is not supported in IE/Edge. This PR changes that into the "ponyfill" here:
https://github.com/feross/fromentries/blob/master/index.js
Also, while fixing this, I noticed that for agencies with multiple domains (e.g. DTA), the form save splits on `\n` to create an array of domains from the textarea input, but it doesn't strip out the `\r`, so domains that weren't on the last line were saving with an incorrect value - this PR fixes that by trimming out whitespace from each domain. Also, it was allowing empty lines to create empty domain values, which this PR also fixes.
> Fix admin agency editing for Edge

- apps/marketplace/components/BuyerBriefFlow/BuyerEvaluationCriteriaStage.js
This will be solving 3 problems. 
1) described in the jira ticket
2) When there is a blank weighting the error of weights being greater than 0 should no longer show up
3. noEmptyCriteriaNiceToHave - had the wrong message this whole time. Changing the error message to reflect the proper error message
> mar-3465.3

- apps/marketplace/components/Teams/Flows/TeamLeadNameDescription.js
- apps/marketplace/components/Teams/Flows/TeamMemberNameDescription.js
This PR rewords the description text for the team lead and team member selectors, so there is no longer a reference to the user needing to be from a specific email domain, since the check is now done by agency id and no longer reliant on email domain.
Since the release of the `agency_domain` work (i.e. an agency being able to have multiple domains), this was broken and displayed an empty value.
> Change team lead and member description text

- src/bundles/Search/components/Catalogue/Catalogue.js
Removing references of 'Areas of expertise' to 'Categories' in the seller catalogue.
There are other references of 'Areas of Expertise' in the code but these pages aren't accessed by the seller. I put in a ticket to remove dead code.
> Mar-3954 Remove area of expertise in the seller catalogue

- apps/marketplace/components/BuyerSpecialist/BuyerSpecialistTimeframesAndBudgetStage.js
- apps/marketplace/components/validators.js
This PR will fix up a few things: 
1.  When a user puts in a date that is in the past, the error message will state **'You must enter a start date that is in the future.'** This will not remove or replace validStartDate function, instead this will only appear when the date is invalid, for instance a leap year.
2. When the form is empty, instead of getting 2 messages that says _'you must enter a valid start date'_ and _'Enter an estimated start date for the opportunity'_, it will only show _'Enter an estimated start date'_ 
The 2nd point wasn't in the ticket but I did it anyway since it didn't make much sense. I updated the UI automation test to reflect this.
> Mar 3977 - Unclear error message - valid date unspecified

- apps/marketplace/components/BuyerSpecialist/BuyerSpecialistTimeframesAndBudgetStage.js
- apps/marketplace/components/validators.js
This PR will fix up a few things:
When a user puts in a date that is in the past, the error message will state 'You must enter a start date that is in the future.' This will not remove or replace validStartDate function, instead this will only appear when the date is invalid, for instance a leap year.
When the form is empty, instead of getting 2 messages that says 'you must enter a valid start date' and 'Enter an estimated start date for the opportunity', it will only show 'Enter an estimated start date'
The 2nd point wasn't in the ticket but I did it anyway since it didn't make much sense. I updated the UI automation test to reflect this.
> Mar 3977 adding validation message for dates in the past within Specialist Brief

- apps/marketplace/components/Brief/OpportunityHistory.js
- apps/marketplace/pages/OpportunityHistoryPage.js
This pull request fixes a problem where part of the base name of the router was becoming undefined when navigating to and from different routes.
Related - https://github.com/AusDTO/dto-digitalmarketplace-api/pull/758
Addresses MAR-4140
> Use framework in the links used by edit history components

- apps/marketplace/components/Brief/Edit/EditOpportunity.js
- apps/marketplace/components/BuyerBriefFlow/Overview.js
- apps/marketplace/components/Opportunity/Opportunity.js
- apps/marketplace/components/Opportunity/OpportunityInfoCard.js
- apps/marketplace/components/Opportunity/OpportunitySpecialistInfoCard.js
- apps/marketplace/pages/BuyerBriefOverviewPage.js
- apps/marketplace/pages/OpportunityPage.js
This pull request changes the behaviour of the cancel edits button which currently links to the overview even if the user was previously on the opportunity page.  The user will now be taken to the previous page that they were on or the overview if no previous page has been detected (eg. page is opened in a new tab).
Addresses MAR-4133
> Return user to previous page on cancel edits

- apps/marketplace/components/Brief/Edit/EditOpportunityTable.js
- apps/marketplace/main.scss
> Add top border to first row in edit opportunity table

- apps/marketplace/components/Brief/Edit/EditOpportunityTable.js
- apps/marketplace/components/Brief/Edit/EditOpportunityTable.scss
- apps/marketplace/main.scss
This pull request vertically aligns content in the edit opportunity table so that headers and actions sit at the top.
Addresses MAR-4153
> Vertically align edit opportunity table content

- apps/marketplace/components/Brief/Edit/EditedOpportunity.js
This pull request changes the message of the page alert to display the seller's name if only one seller has been added and only sellers were edited.
Addresses MAR-4161
> Update content for edited opportunity page alert

- apps/shared/validators.js
- src/validators.js
A seller was unable to apply for an opportunity due to an invalid phone number for their authorised representative.  It looks like this might be due to their number including a `-` character.  This pull request makes the phone number validators consistent across files in this repo and with what the API uses.
Addresses MAR-4172
> Make phone number validators consistent

- apps/marketplace/components/Brief/SummaryComparison.js
> Preserve white space when comparing summaries

- apps/marketplace/components/BuyerBriefFlow/Overview.js
This pull request adds a step to the Overview for draft and closed opportunities.
Addresses MAR-4183
> Add edit live opportunity step to Overview

- apps/marketplace/components/Brief/Edit/EditOpportunitySummary.js
This pull request increases the size of the text area used when editing summaries for non-specialist opportunities.
Addresses MAR-4187
> Make summary text area the same size for all types of opportunities

- apps/shared/validators.js
- src/validators.js
When #953 was released, Rollbar started reporting `TypeError: match is not defined`.  I think this is because the `match` function was being called for values other than strings, like a seller's maximum daily rate. This pull request will skip the check if a string is not passed to the validator.
> Check for null characters if value is a string

- apps/marketplace/components/Brief/Edit/AddSellerActions.js
- apps/marketplace/components/Brief/Edit/AddSellerActions.scss
- apps/marketplace/components/ItemSelect/SelectedItems.js
- apps/marketplace/components/ItemSelect/SelectedItems.scss
- apps/marketplace/components/Teams/Flows/TeamLeadActions.js
- apps/marketplace/components/Teams/Flows/TeamMemberActions.js
- apps/marketplace/components/Teams/Flows/TeamStages.scss
This pull request supports separate styles for selected items that are associated with the ItemSelect component.
Addresses MAR-4162
> Move link to remove sellers when editing on smaller screens

- apps/marketplace/components/Brief/OpportunityHistory.js
- apps/marketplace/components/Brief/OpportunityHistory.scss
- apps/marketplace/main.scss
This pull request adjusts the styles that affect the timestamp and list of edits on the history page.
Addresses MAR-4242
> Update edit history styles

- apps/marketplace/actions/briefActions.js
- apps/marketplace/components/Brief/OpportunityHistory.js
- apps/marketplace/pages/OpportunityHistoryPage.js
- apps/marketplace/reducers/briefReducers.js
This pull request is related to a bug in the API where invited sellers were being removed before the function call to check if only sellers were edited.  This meant that users would be shown the page alert on the opportunity's page notifying them that edits had been made but there would be no edit history to display if only sellers had been edited.
Additional logic has been added to show the appropriate content based on the user's role, whether they're logged in and if they can respond to the opportunity.
Related to https://github.com/AusDTO/dto-digitalmarketplace-api/pull/771.
Addresses MAR-4275
> Show appropriate edit history content

- apps/marketplace/components/Opportunity/Opportunity.js
This pull request simplifies the logic to determine when documents and questions are shown on the opportunity page.  It's intended to prevent sellers from accessing documents or asking questions if they can't respond to an opportunity (by design) or because they're not assessed.
Relates to: https://github.com/AusDTO/dto-digitalmarketplace-api/pull/778
Addresses MAR-4243
> Show opportunity documents and questions if seller can respond

- apps/marketplace/actions/supplierActions.js
- apps/marketplace/components/Brief/Edit/EditOpportunitySellers.js
- apps/marketplace/components/BuyerRFX/BuyerRFXSelectStage.js
- apps/marketplace/components/BuyerSpecialist/BuyerSpecialistSelectStage.js
- apps/marketplace/components/BuyerTraining/BuyerTrainingSelectStage.js
- apps/marketplace/components/SellerSelect/SellerSelect.js
This pull request adds the brief ID to the seller search request.  This is used to determine if recruiters can be invited to the opportunity.  Recruiters can only respond to specialist opportunities.
Relates to: https://github.com/AusDTO/dto-digitalmarketplace-api/pull/779
Addresses MAR-4309
> Add brief ID to seller search request

- apps/marketplace/components/NotFound.js
- apps/marketplace/constants/messageConstants.js
- apps/shared/NotFound.js
- apps/shared/SaveError.js
- src/bundles/Collaborate/components/Code/Code.js
- src/bundles/Collaborate/components/ProjectSubmitConfirmation/ProjectSubmitConfirmation.js
- src/bundles/SellerRegistration/components/SignupForm/SignupForm.js
- src/shared/NotFound.js
- src/shared/SaveError.js
- src/shared/SellerProfile/Body.js
This pull request replaces references to the `marketplace@digital.gov.au` email address with `marketplace@dta.gov.au` to match the address that is configured with Zendesk.
> Replace @digital.gov.au with @dta.gov.au

- apps/marketplace/components/SellerAssessment/SellerAssessmentEvidenceStage.js
This pull request updates the content used for the label and description of the referee field that sellers must complete when submitting evidence for a category assessment.
Addresses MAR-4329
> Update referee label and description 

- apps/marketplace/components/BuyerATM/BuyerATMIntroductionStage.js
- apps/marketplace/components/BuyerRFX/BuyerRFXIntroductionStage.js
- apps/marketplace/components/BuyerSpecialist/BuyerSpecialistIntroductionStage.js
- apps/marketplace/components/BuyerSpecialist/BuyerSpecialistStages.js
- apps/marketplace/components/BuyerTraining/BuyerTrainingIntroductionStage.js
This pull request: 
1. Makes the content consistent across the `Introduction` stage of all opportunities
2. Updates the file size for the new question templates that will be uploaded to Zendesk
3. Updates the stage title to match the page heading for the specialist `Evaluation criteria` stage
> Make intro content consistent across opportunities

- apps/marketplace/actions/appActions.js
- apps/marketplace/actions/resetPasswordActions.js
This pull request clears the CSRF token if it's invalid after a login or password reset attempt.
> HM-3233: Clear CSRF token when invalid

- apps/marketplace/components/Brief/BriefSpecialistResponseForm2.js
This pull request hides the desirable criteria section in the seller response flow if no desirable criteria exist.  It also renders textfields only if the criterion has been defined (ie. is not an empty string).
> HM-2845: Hide empty desirable criteria

- manifest-prod.yml
- manifest.alpha.yml
- manifest.pc.yml
- manifest.rc.yml
- manifest.yml
The following error was encountered during deployment of the app:
> Unable to install node: no match found for 10.x in [12.22.5 12.22.6 14.17.5 14.17.6 15.13.0 15.14.0 16.7.0 16.8.0]
This is most likely caused by an update to the Cloud Foundry buildpack which dropped support for version 10.x.
> HM-3487: Use buildpack with Node.js v10

- apps/marketplace/components/Insights/NumberOfSellersPerCategory.js
- apps/marketplace/components/Insights/WhoIsBuying.js
This pull request adds more colours to the `Who is buying?` and `Number of sellers per category` charts to account for expanded data.  The height of the `Who is buying?` chart has been increased to improve how it renders on smaller screens.
> HM-3650: Add colours to insights

- src/bundles/SellerRegistration/components/RecruiterForm/RecruiterForm.css
- src/bundles/SellerRegistration/components/RecruiterForm/RecruiterForm.js
This pull request adds checkboxes to toggle the display of labour hire sections on the recruiter stage in the application flow. When a checkbox is not selected after being selected, the labour hire licence data for that state will be reset.
> HM-4135: Adjust display of labour hire licences

- apps/marketplace/components/BuyerDashboard/BuyerDashboardHeader.js
- apps/marketplace/components/Onboarding/BuyerOnboarding.js
- apps/marketplace/components/Onboarding/__snapshots__/UserOnboarding.test.js.snap
This pull request replaces instances of Outcome with Professional Services and Consulting.  It includes:
- Create new request accordion on the buyer dashboard
- Onboarding text shown to new buyers that sign up
> HM-4457: Replace 'Outcome' with 'Professional Services and Consulting'

- apps/marketplace/components/BuyerSpecialist/BuyerSpecialistSelectStage.js
- apps/marketplace/components/SellerSelect/SellerSelect.js
This pull request reorders components on the "Who Can Respond" stage so the radio list appeared before the category dropdown.
The changes also include:
- extra props for PanelCategorySelect component (description - text displayed underneath field label; helpLabel - text displayed in hyperlink for categories & rates page)
> HM-4374: Reorder components on Who Can Respond stage

- apps/marketplace/components/BuyerDashboard/BuyerDashboardHeader.js
- apps/marketplace/pages/SellerDashboardPage.js
page alerts for changes to ICT labour hire/category 
buyer dashboard and seller dashboard - top of page
“click here” links as below:
Seller link -> [New Digital Marketplace Category - Labour Hire](https://mailchi.mp/3d8298eb0100/new-digital-marketplace-category-platforms-integration-988033?e=%5BUNIQID%5D) 
Buyer link -> [New Digital Marketplace Category - Labour Hire](https://mailchi.mp/ae94e5dd228d/new-digital-marketplace-category-platforms-integration-988037) 
BANNER CONTENT
Prior to launch - 9am 17/02
"Updates to the Digital Marketplace"
"We will soon make some updates to the Digital Marketplace including the creation of the new ICT Labour Hire category, and the renaming of "Specialist" and "Outcome" opportunities. For more information on how this affects you, click here." (Link …
> Page alerts hm 4452 Page alerts for changes to ICT labour hire

- apps/marketplace/components/Brief/BriefDownloadWorkOrder.js
- apps/marketplace/components/Insights/DailyRates.js
- apps/marketplace/components/Insights/ResponsesPerOpportunity.js
- apps/marketplace/components/Insights/SpecialistPercent.js
This pull request replaces references to `specialist` with `ICT Labour Hire` on the insights and download work order pages.
> HM-4592: Content changes for insights and download work order pages

- apps/marketplace/components/SellerAssessment/SellerAssessmentCriteriaStage.js
This pull request removes an unnecessary dollar symbol from the validation error message when the number of criteria selected for a seller assessment has exceed the limit.
**Preview:**
> HM-2867: Fix validation error message by removing dollar symbol

- apps/marketplace/components/BuyerDashboard/BuyerDashboardHeader.js
- apps/marketplace/pages/SellerDashboardPage.js
This pull request removes the page alerts on the buyer and seller dashboards which announced the ICT Labour Hire release.
> HM-4805: Remove page alerts for ICT Labour Hire changes

- src/bundles/SellerRegistration/components/RecruiterForm/RecruiterForm.js
This pull request removes a redundant notice which is displayed when a recruiter seller changes to a different seller type when editing their profile.
> Remove category notice on recruiter form
